# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e02fe8be313704f20212b17a07c79ba1"
name = "microservice-app"
application_url = "https://localhost:3458/"
embedded = true
handle = "microservice-app-3"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, read_products"

[auth]
redirect_urls = [ "https://localhost:3458/api/auth" ]

[pos]
embedded = false
