apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-service
  namespace: microservice-app
  labels:
    app: app-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-service
  template:
    metadata:
      labels:
        app: app-service
    spec:
      containers:
      - name: app-service
        image: microservice-app/app-service:latest
        imagePullPolicy: Never  # For local development
        ports:
        - containerPort: 3003
          name: http
        env:
        - name: PORT
          value: "3003"
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: NODE_ENV
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_PORT
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_NAME
        - name: SHOPIFY_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: SHOPIFY_SERVICE_URL
        livenessProbe:
          httpGet:
            path: /api/app/health
            port: 3003
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/app/health
            port: 3003
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: microservice-app
  labels:
    app: app-service
spec:
  ports:
  - port: 3003
    targetPort: 3003
    name: http
  selector:
    app: app-service
  type: ClusterIP