apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: microservice-app
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: microservice-app/frontend:latest
        imagePullPolicy: Never  # For local development
        ports:
        - containerPort: 80
          name: http
        env:
        - name: REACT_APP_GATEWAY_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: GATEWAY_SERVICE_URL
        - name: REACT_APP_SHOPIFY_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: SHOPIFY_API_KEY
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: microservice-app
  labels:
    app: frontend
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: frontend
  type: ClusterIP