apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: microservice-app
  labels:
    app: gateway-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
      - name: gateway-service
        image: microservice-app/gateway-service:latest
        imagePullPolicy: Never  # For local development
        ports:
        - containerPort: 3001
          name: http
        env:
        - name: PORT
          value: "3001"
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: NODE_ENV
        - name: AUTH_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: AUTH_SERVICE_URL
        - name: APP_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: APP_SERVICE_URL
        - name: SHOPIFY_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: SHOPIFY_SERVICE_URL
        - name: WEBHOOK_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: WEBHOOK_SERVICE_URL
        # Shopify API credentials for session token validation
        - name: SHOPIFY_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: SHOPIFY_API_KEY
        - name: SHOPIFY_API_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: SHOPIFY_API_SECRET
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: microservice-app
  labels:
    app: gateway-service
spec:
  ports:
  - port: 3001
    targetPort: 3001
    name: http
  selector:
    app: gateway-service
  type: LoadBalancer  # External access