apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopify-service
  namespace: microservice-app
  labels:
    app: shopify-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shopify-service
  template:
    metadata:
      labels:
        app: shopify-service
    spec:
      containers:
      - name: shopify-service
        image: microservice-app/shopify-service:latest
        imagePullPolicy: Never  # For local development
        ports:
        - containerPort: 3004
          name: http
        env:
        - name: PORT
          value: "3004"
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: NODE_ENV
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_PORT
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_NAME
        - name: SHOPIFY_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: SHOPIFY_API_KEY
        - name: SHOPIFY_API_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: SHOPIFY_API_SECRET
        - name: SHOPIFY_APP_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: SHOPIFY_APP_URL
        - name: SHOPIFY_SCOPES
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: SHOPIFY_SCOPES
        livenessProbe:
          httpGet:
            path: /api/shopify/health
            port: 3004
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/shopify/health
            port: 3004
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: shopify-service
  namespace: microservice-app
  labels:
    app: shopify-service
spec:
  ports:
  - port: 3004
    targetPort: 3004
    name: http
  selector:
    app: shopify-service
  type: ClusterIP