apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-service
  namespace: microservice-app
  labels:
    app: webhook-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webhook-service
  template:
    metadata:
      labels:
        app: webhook-service
    spec:
      containers:
      - name: webhook-service
        image: microservice-app/webhook-service:latest
        imagePullPolicy: Never  # For local development
        ports:
        - containerPort: 3005
          name: http
        env:
        - name: PORT
          value: "3005"
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: NODE_ENV
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_PORT
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: WEBHOOK_DB_NAME
        - name: SHOPIFY_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: SHOPIFY_API_KEY
        - name: SHOPIFY_API_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: SHOPIFY_API_SECRET
        - name: SHOPIFY_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: SHOPIFY_WEBHOOK_SECRET
        livenessProbe:
          httpGet:
            path: /api/webhooks/health
            port: 3005
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/webhooks/health
            port: 3005
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: microservice-app
  labels:
    app: webhook-service
spec:
  ports:
  - port: 3005
    targetPort: 3005
    name: http
  selector:
    app: webhook-service
  type: ClusterIP