apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: microservice-app
data:
  NODE_ENV: "production"
  # Production specific configs
  SHOPIFY_EMBEDDED: "true"
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopify-service
  namespace: microservice-app
spec:
  template:
    spec:
      containers:
      - name: shopify-service
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: microservice-app
spec:
  template:
    spec:
      containers:
      - name: auth-service
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"