apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: microservice-app
data:
  # Database Configuration - Single shared database
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_USERNAME: "postgres"
  DB_NAME: "microservice_app"
  WEBHOOK_DB_NAME: "webhook_service"
  
  # Redis Configuration
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  
  # Service URLs
  SHOPIFY_SERVICE_URL: "http://shopify-service:3004"
  AUTH_SERVICE_URL: "http://auth-service:3002"
  APP_SERVICE_URL: "http://app-service:3003"
  WEBHOOK_SERVICE_URL: "http://webhook-service:3005"
  GATEWAY_SERVICE_URL: "http://gateway-service:3001"
  
  # Service Ports
  AUTH_PORT: "3002"
  APP_PORT: "3003"
  GATEWAY_PORT: "3001"
  SHOPIFY_PORT: "3004"
  WEBHOOK_PORT: "3005"
  
  # Application Configuration
  NODE_ENV: "development"
  SHOPIFY_SCOPES: "write_products,read_products"
  SHOPIFY_EMBEDDED: "true"
  BACKEND_PORT: "3001"
  
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: microservice-app
type: Opaque
data:
  # Base64 encoded values (echo -n 'value' | base64)
  DB_PASSWORD: cGFzc3dvcmQ=  # password
  SHOPIFY_API_KEY: ZTAyZmU4YmUzMTM3MDRmMjAyMTJiMTdhMDdjNzliYTE=  # e02fe8be313704f20212b17a07c79ba1
  SHOPIFY_API_SECRET: NzMyMDYxNTk2ZGY3ZTkyNjM5MWY2MGQxNDcxZTY5Zjc=  # 732061596df7e926391f60d1471e69f7
  SHOPIFY_APP_URL: aHR0cHM6Ly95b3VyLWFwcC1kb21haW4uY29t  # https://your-app-domain.com
  SHOPIFY_WEBHOOK_SECRET: d2ViaG9va19zZWNyZXRfa2V5  # webhook_secret_key